name: s3-deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install Dependencies
        run: npm install
      - name: Build Content
        run: npm run content
      - name: Lint
        run: npm run lint
      - name: Build React App
        run: npm run build
      - name: Deploy app build to S3 bucket
        run: aws s3 sync dist/ s3://vanessapoppe.me --acl public-read
